# Generated by Django 5.1.4 on 2025-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_created_by_user_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('admin', 'Admin'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
